name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🚀 Improvement'
    label: 'ti'
change-template: '- $CHANGE_TITLE (#$PULL_REQUEST_ID) @$AUTHOR'
version-resolver: 'github-tag'
